### ISSUE TITLE
3.0 Deprecations and removals

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#970]
I'll list them all here including ones we've already completed or may not need to address, just to make sure none slip through the cracks. Per https://jquery.com/upgrade-guide/3.0/ we have these:

### Deprecated
* [ ] jQuery.fx.interval (PR #969)
* [ ] .toggleClass() and .toggleClass(Boolean)
* [x] jQuery.unique renamed to jQuery.uniqueSort
* [x] jQuery.parseJSON
* [x] .ready() signatures other than jQuery( fn )
* [ ] easing parameters (issue #766)
* [ ] .bind() and .delegate()
* [ ] jQuery.expr[":"] and jQuery.expr.filters (never documented?)

### Removed
* [x] jQuery().context and .selector
* [x] .andSelf()
* [ ] jqXHR.success, .error, and .complete
* [ ] $(document).on("ready", fn) (never documented?)
* [ ] .load(), .unload(), and .error() (marked removed, do we need text?)
* [ ] event.pageX and event.pageY normalization (not sure we need changes)

### Features
* [x] jQuery.escapeSelector
* [ ] jQuery.ready promise-consumable (issue #205)
* [ ] jQuery.Deferred Promises/A+ compat
* [ ] jQuery.when() consumes thenables (issue #921)
* [ ] .animate() uses requestAnimationFrame
* [ ] settings argument signature for jQuery.get() and .post() (showing 1.12?)
* [ ] SVG support for .addClass(), .removeClass(), and .toggleClass() (showing 1.12?)
